# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbd7a352d453783aa04afc38ed1b3561b62eeaf3b8a492252b3b7873743b53564f651de4387299e15158be9b51d532946f8d54b1b71b9815c3dd1e30eadf6148

test:
  secret_key_base: 6e1265e132ae0ee2c2109f5fe6b8f9b22cbdd5f19630cc6cdc4a74a95bb8df0a27915a65d913e253468d3be61ea43a81d0de24a5ff244667a5472ec78a8cdd7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
